org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
loader_version=0.16.5
loom_version=1.7-SNAPSHOT

# Mod - author: Mikasa
# version format: fabric-<mc>-<mod> -> Mikasa-bars-fabric-1.21.1-1.3.jar
version=fabric-1.21.1-1.3
maven_group=com.mikasa
archives_base_name=Mikasa-bars

fabric_api_version=0.102.1+1.21.1
